# Generated by Django 4.2.30 on 2026-05-16 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowers',
            fields=[
                ('borrower_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reference_id', models.CharField(max_length=200)),
                ('borrower_name', models.CharField(max_length=200)),
                ('borrower_contact', models.CharField(max_length=200)),
                ('borrower_address', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_borrowers',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'tbl_categories',
            },
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('equipment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('equipment_code', models.CharField(max_length=200, unique=True)),
                ('equipment_name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipment_photos/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='ems_app.categories')),
            ],
            options={
                'db_table': 'tbl_equipments',
            },
        ),
        migrations.CreateModel(
            name='BorrowRecords',
            fields=[
                ('record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('borrower_name_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('borrower_contact_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('equipment_name_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('equipment_code_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('category_name_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('expected_return', models.DateField()),
                ('actual_return', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned')], default='borrowed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_records', to='ems_app.borrowers')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_records', to='ems_app.equipments')),
            ],
            options={
                'db_table': 'tbl_borrow_records',
            },
        ),
    ]
