# Generated by Django 4.2.30 on 2026-05-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecords',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='equipments',
            name='total_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('maintenance', 'Under Maintenance')], default='available', max_length=20),
        ),
    ]
