# Generated by Django 4.2.30 on 2026-05-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0002_borrowrecords_quantity_equipments_total_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipments',
            name='status',
        ),
    ]
